#
# This is the HTTPS version of the Smilr ingress
# Use if you've set up cert-manager and have a valid cert issued
#
# !IMPORTANT! Change the domain names in the host/hosts sections to match your real 
# DNS zone, as created when you deployed AKS with the HTTP application routing add-on

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "smilr-ingress"
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # !CHANGE THIS! Remove if using a static pre-created cert
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    # !CHANGE THIS! To match the DNS zone / domain name you are using
    - smilr.changeme.changeme.aksapp.io
    # !CHANGE THIS! If using a pe-created cert, put the secret name here
    secretName: smilr-cert-staging
  rules:
  # !CHANGE THIS! To match the DNS zone / domain name you are using
  - host: smilr.changeme.changeme.aksapp.io
    http:
      paths:
      - path: /api
        backend:
          serviceName: data-api
          servicePort: 80
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
