#
# Deploy the front end microservice which serves the client app
# Basic version
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-pods

        # !CHANGE THIS! To your real image reference for the frontend 
        image: changeme.azurecr.io/smilr/frontend:stable
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:       
        - name: API_ENDPOINT
          # !CHANGE THIS! To the external IP of data-api service or DNS name if using external DNS, don't forget /api 
          value: http://12.34.56.89/api

        resources:
          limits:
            memory: "64M"
            cpu: "0.125"

---

# ------------------- Loadbalancer ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: frontend
  annotations:
    # !CHANGE THIS! To your real DNS domain
    external-dns.alpha.kubernetes.io/hostname: smilrbasic.56539f01234e4e00981e.westeurope.aksapp.io
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: frontend