{{- $fullName := include "smilr.fullname" . -}}
{{- $tlsEnable := (or .Values.ingress.certIssuer .Values.ingress.certName) -}}

{{ if .Values.ingress.domainSuffix }}
#
# Ingress for host based routing, release name prefixed 
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{ if .Values.ingress.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
    {{ end }}
    {{ if $tlsEnable }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{ else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{ end }}
spec:
  {{ if $tlsEnable }}
  tls:
  - hosts:
    - "{{ $fullName }}.{{ .Values.ingress.domainSuffix }}"
    {{ if .Values.ingress.certName }}
    secretName: {{ .Values.ingress.certName }}
    {{ else }}
    secretName: "{{ $fullName }}"
    {{ end }}
  {{ end }}
  rules:
  - host: "{{ $fullName }}.{{ .Values.ingress.domainSuffix }}"
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ $fullName }}-data-api
          servicePort: 80
      - path: /
        backend:
          serviceName: {{ $fullName }}-frontend
          servicePort: 80

{{ else }}
#
# Ingress for path URL based routing, no DNS required only ingress IP
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}-api"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/api"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}/api"
        backend:
          serviceName: {{ $fullName }}-data-api
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}-frontend"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Release.Name }}"
        backend:
          serviceName: {{ $fullName }}-frontend
          servicePort: 80    
{{ end }}
