version: '3'

services:
  api:
    image: ${DOCKER_REG}smilr-orleans/api
    ports:
      - "4000:4000"
    environment: 
      - Orleans__ConnectionString
      - Orleans__ClusterId=smilr-docker
      - Orleans__SiloHost=silo      
    build:
      context: .
      dockerfile: API/Dockerfile
  silo:
    image: ${DOCKER_REG}smilr-orleans/silo
    environment: 
      - Orleans__ConnectionString
      - Orleans__ClusterId=smilr-docker
    build:
      context: .
      dockerfile: Silo/Dockerfile
