#
# Azure Pipelines
# - Deploy to Azure Container Instances across multiple stages
# Ben C, 2019
#
name: $(Date:yyyy-MM-dd)$(Rev:.rr)
trigger: none
pr: none

schedules:
- cron: "15 5 * * *"
  displayName: Daily build
  branches:
    include:
    - master  
  always: true

# NOTE! The 'shared-variables' variable group must be pre-created and populated
# - Expected variables: acr-connection
variables:
  - group: shared-variables
  - name: cleanup
    value: false
  - name: resGroupPrefix
    value: Temp.Smilr
  - name: location
    value: westeurope

stages:
#
# Deploy stage - test environment
#
- stage: deployToTest
  displayName: Deploy to Test
  
  variables:
    dns-prefix: smilr-$(Build.BuildId)-test

  jobs:
  - template: templates/deploy-aci-arm.yml
    parameters:
      envName: ACI-Test
      location: $(location)
      imageTag: latest
      resGroupPrefix: $(resGroupPrefix)
      dnsPrefix: $(dns-prefix)

  - template: templates/run-postman-tests.yml
    parameters:
      dependsOn: deployWithACI
      apiHost: $(dns-prefix)-api.$(location).azurecontainer.io
      frontHost: $(dns-prefix)-frontend.$(location).azurecontainer.io

#
# Deploy stage - staging environment
#
- stage: deployToStaging
  displayName: Deploy to Staging

  variables:
    dns-prefix: smilr-$(Build.BuildId)-staging

  jobs:
  - template: templates/deploy-aci-arm.yml
    parameters:
      envName: ACI-Staging
      location: $(location)
      imageTag: latest
      resGroupPrefix: $(resGroupPrefix)
      dnsPrefix: $(dns-prefix)

  - job: loadtestJob
    displayName: Run Load Test
    dependsOn: deployWithACI
    steps:
      - bash: |
          chmod a+x *.sh
          ./load-front.sh http://$(dns-prefix)-frontend.$(location).azurecontainer.io 30
          ./load-api.sh http://$(dns-prefix)-api.$(location).azurecontainer.io 20
        displayName: Call loadtest scripts
        workingDirectory: etc/loadtest

      - publish: etc/loadtest/results
        artifact: loadtest-results

#
# Deploy stage - prod environment
#
- stage: deployToProduction
  displayName: Deploy to Production
  
  variables:
    dns-prefix: smilr-$(Build.BuildId)-prod

  jobs:
  - template: templates/deploy-aci-arm.yml
    parameters:
      envName: ACI-Production
      location: $(location)  
      imageTag: latest
      resGroupPrefix: $(resGroupPrefix)
      dnsPrefix: $(dns-prefix)

#
# Cleanup stage - remove resources after run
#
- stage: cleanup
  displayName: Remove Resources
  condition: eq(variables['cleanup'], 'true')

  jobs:
  - job: clanupJob
    displayName: Remove Resources Job
    steps:
      - checkout: none
      - task: AzureCLI@1
        continueOnError: true
        inputs:
          azureSubscription: $(azure-connection)
          scriptLocation: inlineScript
          inlineScript: |
            az group delete -g $(resGroupPrefix).ACI-Production --yes --no-wait
            az group delete -g $(resGroupPrefix).ACI-Staging --yes --no-wait
            az group delete -g $(resGroupPrefix).ACI-Test --yes --no-wait