#
# Azure Pipelines
# - Deploy to Kubernetes (AKS) using Helm chart
# Ben C, 2019
#
name: $(Date:yyyy-MM-dd)$(Rev:.rr)
trigger:
  branches:
    include: 
    - master
  paths:
    include:
    - pipelines/deploy-aks.yml
    - pipelines/templates/helm-deploy.yml
    - kubernetes/helm/*

pr:
  branches:
    include: 
    - master
  paths:
    include:
    - pipelines/deploy-aks.yml
    - pipelines/templates/helm-deploy.yml
    - kubernetes/helm/*

resources: 
  pipelines:
  - pipeline: buildpipeline
    source: Build and push to ACR
    trigger: true

# NOTE! The 'shared-variables' variable group must be pre-created and populated
# - Expected variables: aks-connection, acr-connection, azure-connection, aks-resgrp
variables:
  - group: shared-variables
  - name: dns-suffix
    value: 'kube.benco.io'

stages:
# *************************************************************************************
# Deploy stage 1 - AKS test namespace
# *************************************************************************************
- stage: deployToTest
  condition: eq(variables['Build.SourceBranchName'], 'master')
  displayName: AKS Test

  jobs:
  - template: templates/helm-deploy.yml
    parameters:
      envName: test

  - template: templates/run-postman-tests.yml
    parameters:
      dependsOn: deployToAKS
      apiHost: 'test-$(Build.BuildId)-smilr.$(dns-suffix)'
      frontHost: 'test-$(Build.BuildId)-smilr.$(dns-suffix)'

# *************************************************************************************
# Deploy stage 2 - AKS staging namespace
# *************************************************************************************
- stage: deployToStaging
  condition: eq(variables['Build.SourceBranchName'], 'master')
  displayName: AKS Staging

  jobs:
  - template: templates/helm-deploy.yml
    parameters:
      envName: staging

  - template: templates/run-loadtest.yml
    parameters:
      dependsOn: deployToAKS
      apiHost: 'staging-$(Build.BuildId)-smilr.$(dns-suffix)'
      frontHost: 'staging-$(Build.BuildId)-smilr.$(dns-suffix)'

# *************************************************************************************
# Deploy stage 3 - AKS production namespace
# *************************************************************************************
- stage: deployToProduction
  condition: eq(variables['Build.SourceBranchName'], 'master')
  displayName: AKS Production

  jobs:
  - template: templates/helm-deploy.yml
    parameters:
      envName: prod
