parameters:
  envName: ''
  
jobs:
- deployment: deployToAKS
  displayName: Deploy to namespace ${{ parameters.envName }}
  # Dot here is very important, it targets the namespace in the environments view UI
  environment: AKS-${{ parameters.envName }}.${{ parameters.envName }}

  pool:
    vmImage: ubuntu-latest

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - task: HelmInstaller@1
          displayName: 'Install Helm version'
          inputs:
            helmVersionToInstall: 2.14.0
        
        - task: HelmDeploy@0
          displayName: 'Helm update dependencies'
          inputs:
            azureSubscriptionEndpoint: $(azure-connection)
            azureResourceGroup: $(aks-resgrp)
            kubernetesCluster: $(aks-cluster)
            command: dependency
            arguments: 'update kubernetes/helm/smilr'

        - task: KubernetesManifest@0
          displayName: Bake manifests from Helm chart
          name: bake
          inputs:
            action: bake
            kubernetesServiceConnection: $(aks-connection)
            releaseName: '${{ parameters.envName }}-$(Build.BuildId)'
            helmChart: kubernetes/helm/smilr
            overrides: |
              registryPrefix:$(acr-name).azurecr.io/
              dataApi.imageTag:$(image-tag)
              frontend.imageTag:$(image-tag)
              mongo.usePersistence:false

        - task: KubernetesManifest@0
          displayName: Deploy manifests
          inputs:
            kubernetesServiceConnection: $(aks-connection)
            namespace: ${{ parameters.envName }}
            manifests: $(bake.manifestsBundle)
