parameters:
  envName: ''
  
jobs:
- deployment: deployToAKS
  displayName: Deploy to namespace ${{ parameters.envName }}
  # Dot here is very important, it targets the namespace in the environments view UI
  environment: AKS-${{ parameters.envName }}.${{ parameters.envName }}

  pool:
    vmImage: ubuntu-latest

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - task: HelmInstaller@1
          displayName: 'Install Helm version'
          inputs:
            helmVersionToInstall: 2.14.0
        
        - task: HelmDeploy@0
          displayName: 'Helm update dependencies'
          inputs:
            azureSubscriptionEndpoint: $(azure-connection)
            azureResourceGroup: $(aks-resgrp)
            kubernetesCluster: $(aks-connection)
            command: dependency
            arguments: 'update kubernetes/helm/smilr'

        - task: HelmDeploy@0
          displayName: 'Helm install Smilr chart'
          inputs:
            connectionType: Kubernetes Service Connection
            kubernetesServiceConnection: $(aks-connection)
            command: upgrade
            releaseName: ${{ parameters.envName }}-$(Build.BuildId)
            chartType: FilePath
            chartPath: kubernetes/helm/smilr
            namespace: ${{ parameters.envName }}
            overrideValues: "registryPrefix=$(acr-name).azurecr.io/,dataApi.imageTag=$(image-tag),frontend.imageTag=$(image-tag),ingress.domainSuffix=$(dns-suffix),ingress.certName=kube-benco-io-cert"