parameters:
  frontHost: ''
  apiHost: ''
  dependsOn: ''

jobs:
  - job: runTestsJob
    dependsOn: ${{ parameters.dependsOn }}
    displayName: 'Integration API tests'

    condition: and(succeeded(), ne(variables['skiptests'], 'true'))

    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self
    
    # Wait until URL is ready or 60 seconds
    - bash: bash etc/bash/urlWait.sh http://${{ parameters.apiHost }}/api 60
      displayName: Wait until ready
    
    # Install Newman CLI tool
    - bash: npm install -g newman --prefix $(System.DefaultWorkingDirectory)
      displayName: Install newman tool
    
    # Run the tests with Newman
    - bash: >
        $(System.DefaultWorkingDirectory)/bin/newman run etc/postman/smilr-api-tests.json
        --reporters junit --iteration-count 3 --timeout 180000 
        --global-var smilr-api-host="${{ parameters.apiHost }}" 
      displayName: Run API integration tests
    
    # Publish test results
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'newman/*.xml'
        testRunTitle: API Tests
      condition: succeededOrFailed()
